# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-12 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='schoolProgram',
            new_name='school_program',
        ),
    ]
