# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160612_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pend', 'Pending'), ('Accpt', 'Accepted'), ('Deny', 'Denied')], max_length=50),
        ),
    ]
