# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 16:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160612_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='GREScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.IntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('quant', models.IntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('write', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='TOEFLScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('listening', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('speaking', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('writing', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='credit_hour',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='student',
            name='current_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SchoolProgram'),
        ),
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(default='2016-05-05', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(default='2016-05-05'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], max_length=50),
        ),
        migrations.AddField(
            model_name='toeflscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='grescore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
