# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160613_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(default='2016-05-05'),
        ),
    ]
