# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160613_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='credit_hours',
            new_name='current_credit_hours',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='end_date',
            new_name='current_end_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gpa',
            new_name='current_gpa',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='start_date',
            new_name='current_start_date',
        ),
    ]
