# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160613_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prev_credit_hours',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='student',
            name='prev_end_date',
            field=models.DateField(default='2016-05-05'),
        ),
        migrations.AddField(
            model_name='student',
            name='prev_gpa',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='student',
            name='prev_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_program', to='main.SchoolProgram'),
        ),
        migrations.AddField(
            model_name='student',
            name='prev_start_date',
            field=models.DateField(default='2016-05-05'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_program', to='main.SchoolProgram'),
        ),
    ]
