# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160613_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='school_level',
            field=models.CharField(default='grad', max_length=50),
            preserve_default=False,
        ),
    ]
