# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_program_school_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='gpa',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='greapti',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='greverbal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='grewriting',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='toefl',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='gpa',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='greapti',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='greverbal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='grewriting',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='toefl',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
