# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160614_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('start_date', models.DateField(default='2016-05-05', null=True)),
                ('end_date', models.DateField(default='2016-05-05', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='program',
            name='greapti',
        ),
        migrations.RemoveField(
            model_name='program',
            name='greverbal',
        ),
        migrations.RemoveField(
            model_name='program',
            name='grewriting',
        ),
        migrations.RemoveField(
            model_name='program',
            name='toefl',
        ),
        migrations.RemoveField(
            model_name='school',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='school',
            name='greapti',
        ),
        migrations.RemoveField(
            model_name='school',
            name='greverbal',
        ),
        migrations.RemoveField(
            model_name='school',
            name='grewriting',
        ),
        migrations.RemoveField(
            model_name='school',
            name='toefl',
        ),
    ]
