# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160614_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprogram',
            name='gpa',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='schoolprogram',
            name='greapti',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='schoolprogram',
            name='greverbal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='schoolprogram',
            name='grewriting',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='schoolprogram',
            name='toefl',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
