# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160618_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subscribed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
