# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_student_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('security_code', models.IntegerField()),
                ('expiration', models.DateField(default='2016-05-05', null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('addr_line1', models.TextField()),
                ('addr_line2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('country', models.TextField()),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Amex', 'Amex'), ('Discover', 'Discover')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
