# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
