# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20160621_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
